### ISSUE TITLE
Automatic sync can´t be deactivated

### ISSUE THREAD

**Issue by OMOSde** [m-vo/contao-facebook-import#12]
If i deactivate the automatic sync and save, then i get the error in the screen.

![mvo_facebook_import](https://user-images.githubusercontent.com/2035628/52279176-40f2e880-2959-11e9-8701-3ff28813e040.png)

The table column is boolean. I think the contao widget 'checkbox' expect a char(1). 

Contao 4.4.34
Bundle is v3.0.3

**Comment by m-vo** [comment]
I see. Looks there might be the need for an ``onsave_callback`` for strict types. I assume the toggle function in the parent view (eye symbol) is working?

I'll try to have to look in this this week.

**Comment by OMOSde** [comment]
I can confirm, that the eye symbol (toggle automatic) is working in my installation.

**Comment by m-vo** [comment]
fixed in c83ce456127c3597d936728a50263b2fa34937e0
