### ISSUE TITLE
Contao 4.6 Issue

### ISSUE THREAD

**Issue by eiswurm** [m-vo/contao-facebook-import#13]
After some Core Updates, I get the following error:

The service "mvo_contao_facebook.listener.datacontainer.facebook_post" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services

on Contao 4.6.14 and mvo/contao-facebook-import 2.2.1

**Comment by m-vo** [comment]
Please update to v3 of the bundle, v2 isn't supported anymore.
