### ISSUE TITLE
Raise Graph API version to 3.3

### ISSUE THREAD

**Issue by mdriverch** [m-vo/contao-facebook-import#15]
Is the module compatible with Facebook Graph API v3.3+ ?

**Comment by m-vo** [comment]
Why do you need the bundle to access the API via a higher version? Currently it's using `v3.1` which [according to Facebook](https://developers.facebook.com/docs/graph-api/changelog/) is still available till 23th Oct 2020. 

Scrolling through the changelog I don't see what should stop us from using the newer version later on (there are some deprecations though that should then be adressed). 

You can try yourself by adjusting this bit: https://github.com/m-vo/contao-facebook-import/blob/e4e84c645483bb0f87053ae2f02bb2fd3fcc2120/src/GraphApi/GraphApiReader.php#L69

**Comment by mdriverch** [comment]
Thank you for your quick answer. Unfortunately, you can no longer create API with 3.1. Facebook adapted it on April 30th. New apps only work with v3.3

The change as you have described does not work. I get the following error message.

Facebook SDK: An error occurred querying edge of entity posts: (#12) type field is deprecated for versions v3.3 and higher [Code 12]

**Comment by m-vo** [comment]
I see.

> Facebook SDK: An error occurred querying edge of entity posts: (#12) type field is deprecated for versions v3.3 and higher [Code 12]

We should probably not handle deprecation warnings as errors. But fixing the deprecations shouldn't be too hard either.

**Comment by mdriverch** [comment]
> We should probably not handle deprecation warnings as errors. But fixing the deprecations shouldn't be too hard either.

Do you see if you have time to fix this?

**Comment by m-vo** [comment]
@minidriverch Could you please check if the changes from 536f14a1773bb7e3882b0ec1c51452db1b9476b6 + 1735299894aac13ae6cb279481ad0aa69fc049d7 work for you? You can install v3.1.0-beta to test things.

**Comment by m-vo** [comment]
v3.1.0 is released
