### ISSUE TITLE
Feature: album

### ISSUE THREAD

**Issue by bastlwastl** [m-vo/contao-facebook-import#17]
It would be great, to get this posts, too.
Or at least the textual content.

**Comment by bastlwastl** [comment]
The album posts are already imported. However, you cannot select `album` in the `Facebook Post List`.

I have modified the files `Version300SetPostTypes.php`, `FacebookPost.php` and `ScrapingInformation.php`.

So you can select album in the Facebook Post List.
This works for me.

![album](https://user-images.githubusercontent.com/1818726/66124712-679b1900-e5e5-11e9-98e9-770443a1e571.jpg)

**Comment by m-vo** [comment]
Sounds reasonable, but we should also scrape and provide the images I guess. Or why would you want to display an album otherwise?

@bastlwastl Do you want to work on a PR?

**Comment by bastlwastl** [comment]
Something's wrong here. The posts I'm interested in are not an album.
The posts are normal status posts with several pictures.
These status posts are marked as `[album]` and are therefore not displayed in the Facebook Post List.
Who declares this post as an album? The extension contao-facebook-import or Facebook?

With the changes of the three files the post will be imported together with a picture and will also be displayed in the Facebook Post List.

Sorry, I'm not a programmer. So I can't help with a PR either.

**Comment by m-vo** [comment]
see #23
