### ISSUE TITLE
Contao 4.9

### ISSUE THREAD

**Issue by markotodic** [m-vo/contao-facebook-import#20]
Hello Mr. Vondano,
did you thought about releasing this bundle for next Contao LTS 4.9?

I did a test on RC1 and I found an issue in Mvo\ContaoFacebookImport\Image\Scraper::scrape() where ImageFactory is throwing an exception as it is expecting $path argument to be absolute.

What are your plans for maintaining this bundle may I ask?

**Comment by m-vo** [comment]
Do you want to contribute a PR?

**Comment by markotodic** [comment]
> Do you want to contribute a PR?

#22

**Comment by m-vo** [comment]
see #21
