### ISSUE TITLE
Could not convert access token.

### ISSUE THREAD

**Issue by Metis77** [m-vo/contao-facebook-import#3]
Our tokens seam to be blocked right now.
Can you help us out with paid support and offering a generic token?

**Comment by m-vo** [comment]
Could you elaborate what you mean with tokens being blocked?

**Comment by Metis77** [comment]
The Graph API Explorer says:
![bildschirmfoto 2018-04-25 um 13 00 28](https://user-images.githubusercontent.com/1408361/39241927-b66f14ec-4888-11e8-8859-a765bab153d7.png)

Maybe this is because of:
https://developers.facebook.com/status/issues/205942813488872/

But I would like to be able to use you plugin.

**Comment by m-vo** [comment]
So when does this message get displayed? You should see an access token in the graph api explorer as soon as you select your app in the dropdown. Choose the respective facebook page from the dropdown below then (if you're not seeing your page there, hit "Get Page Access Token" and grant access.

**Comment by Metis77** [comment]
![bildschirmfoto 2018-04-25 um 13 34 09](https://user-images.githubusercontent.com/1408361/39244046-be49ccb4-488f-11e8-87a3-43b2bbfb6193.png)

**Comment by m-vo** [comment]
Well this is expected, if the access token is invalid. What do you see in the [Graph Api Explorer](https://developers.facebook.com/tools/explorer)? 
 > You should see an access token in the graph api explorer as soon as you select your app in the dropdown. Choose the respective facebook page from the dropdown below then (if you're not seeing your page there, hit "Get Page Access Token" and grant access.

**Comment by Metis77** [comment]
That is what I posted in the first place.

![bildschirmfoto 2018-04-25 um 14 57 05](https://user-images.githubusercontent.com/1408361/39247207-0a31d654-4899-11e8-870f-a199d2ac768f.png)

This might be due to https://developers.facebook.com/status/issues/205942813488872/

**Comment by m-vo** [comment]
I guess it's a FB problem then. :disappointed: 

People are reporting the same thing here: https://stackoverflow.com/questions/49417886/why-does-facebook-graph-api-say-my-account-is-non-active

Are you able to activate your app (if it has the status 'In development') and see if this changes anything? This may trigger a review process, though.

**Comment by Metis77** [comment]
the app is active, but is waiting for "App Review" by Facebook.
That is why I ask, if you can offer us an generic token for your app.

Due to the current problems, other Apps like this one for Wordpress: https://de.wordpress.org/plugins/custom-facebook-feed/
Offer a generic token from the developer:

![bildschirmfoto 2018-04-25 um 15 19 39](https://user-images.githubusercontent.com/1408361/39248431-6074602e-489c-11e8-8604-99ef3c007586.png)

**Comment by m-vo** [comment]
You could in theory use one of the access tokens that are stored in the source code of your referenced plugin. Not sure if this is allowed. (For this to work, you'd probably have to set the token directly in the database for your node.)

But if I understand correctly even then the events import won't work. See the note here: https://developers.facebook.com/docs/apps/review. It seems you'll have to have a reviewed app from now on. Facebook changed this basically overnight. Which annoys the hell outa me.

**Comment by Metis77** [comment]
from: https://developers.facebook.com/docs/apps/review/feature
I read:

> Mit der Pages API kannst du auf Inhalt auf einer Facebook-Seite zugreifen. Standardmäßig kann deine App nur auf Informationen einer Seite, die dir gehört, zugreifen. Wenn du nicht der Eigentümer der Seite bist und auf Informationen anderer Seiten zugreifen möchtest, musst du dieses Feature zur Überprüfung einreichen.

For me this means, I should be able to access pages, that are mine / I am administrator of, without needing a acces token to that specific page.

Also the above named Wordpress APP or [this](https://github.com/postyou/contao-facebook-connector_basic-bundle) Contao solution do need only App ID and App secret to work.

I could extract AppID and Secret from the Wordpress App, but I have no token, that your solutions needs.

**Comment by m-vo** [comment]
The contao bundle your talking about tries to generate an access token with the specified app id and secret. This will fail like it is failing in the graph api explorer. See their note on top of the readme:

> Note: From 4th to 11th of April in 2018 Facebook did some sudden API changes. So the module is not working as expected and some features (e.g. event synchronization) may temporarily or no longer possible. These changes affect all Facebook plugins and we are waiting for further communications from Facebook. Currently we can no longer guarantee the further development of the module.

Like said above: As a temporary workaround and if you don't need event synchronization you could manually set one of the wordpress plugins' access tokens.  But please verify first that this is an allowed way to go as facebook can limit the amount of calls that can be made within a certain timespan and token. You'll find the access tokens in their source code.

**Comment by Metis77** [comment]
ok, than the I can just wait and hope that FB will do something about this.

**Comment by Metis77** [comment]
In the meantime I found out, that I can access the API successfully, if the app is in development mode (not public live). This should be ok, as only my app/website uses this app.

If I enter the access token into contao as suggested by your docs, a long lasting token seams to be generated successfully.

But still nothing is synced.

Entering the same access token into the [Wordpress plugin](https://de.wordpress.org/plugins/custom-facebook-feed/) I mentioned above, sync works perfectly.
But this plugin does not ask for an App ID or App Secret.

I am pretty clueless on how to get sync working again and hope for help.

**Comment by m-vo** [comment]
I'll have a look into this - but I won't manage to do this in the next 2 weeks unfortunately.

**Comment by m-vo** [comment]
I just had a quick look at two of the projects I'm using this extension with: they resumed working like they did before, which basically means the event importing does work again. Also generating a long lived token works for me.

Can you have a look if this is (by any chance) the case for you as well?

**Comment by Metis77** [comment]
I added another Facebook node in your plugin, for testing.

Surprisingly that worked well ... the difference was the amount of posts to sync.
It was set to 200, what seems not to work.

Now it is set to 100, what works well.
Is there a limit?
And what happens, if the 100 posts are synced and new ones are available in Facebook?

May I ask for extending this number and also adding the "add to news" feature, as available for the events?
Of course I would like to invest some money into such features.

What do you think?

**Comment by m-vo** [comment]
Well even 100 seems a hell lot? I haven't used more than ~20 but your use case might be different. Probably facebook paginates the results then and pagination isn't implemented yet.

> And what happens, if the 100 posts are synced and new ones are available in Facebook?

Then older ones get replaced (like rotating logs).

> May I ask for extending this number and also adding the "add to news" feature, as available for the events?
Of course I would like to invest some money into such features.

We can sure talk about this 😃. Would you need both?

**Comment by Metis77** [comment]
> We can sure talk about this 😃. Would you need both?

yes both.
would you like to talk this trough on phone or mail?
do you see my contact details? yours are not available.

**Comment by m-vo** [comment]
I'll send you an email.

**Comment by filipbasara** [comment]
I have a similar issue. 
Followed the necessary steps one by one.
App ID and App Secret seem to work. When entering the long lasting Token it returns an error with `Could not convert access token.`

I'm not sure how to resolve this, as I believe that all the required steps have been done. 

Also in regards to the "add to news" feature. Is this something we can expect as part of the extension at some point? Should I open up a feature request?

Thanks in advance.

**Comment by Metis77** [comment]
@filipbasara did you publish your facebook app, or is it still in "dev mode"?
It should stay in dev mode, if you only want to access facebook pages, that you are the admin of.


You only need to publish (and request review) your facebook app, if you need to read public facebook pages, that you are no admin of.

**Comment by filipbasara** [comment]
@Metis77 Thanks for the reply. Yeah I followed your discussion and left it in dev mode, and yeah I'm reading from a page I'm administrator of.

**Comment by filipbasara** [comment]
My issue resolved itself after revoking and re-adding my admin permissions on facebook.

**Comment by m-vo** [comment]
Importing large amounts of elements is now possible with v3.0.0.
