### ISSUE TITLE
Services for contao-config should be public

### ISSUE THREAD

**Issue by rabauss** [m-vo/contao-facebook-import#7]
Just installed version 3.0 in my testsystem and got first error after one minute...
The service ``mvo_contao_facebook.listener.contao_cron_listener`` should be public. 
Because it's called via contao/config.php

I guess also ``mvo_contao_facebook.listener.database_update`` should be public.
For ``mvo_contao_facebook.datacontainer.facebook_node`` I'm not sure how it's exactly called via contao.

**Comment by theDyingMountain** [comment]
I got the same error in version 3.0. Is there a temporary workaround?

**Comment by m-vo** [comment]
Which Contao version?

**Comment by theDyingMountain** [comment]
4.6.0

**Comment by m-vo** [comment]
fixed in 3.0.2
