### ISSUE TITLE
Foreign keys block uninstall

### ISSUE THREAD

**Issue by rabauss** [m-vo/contao-facebook-import#8]
The foreign keys are blocking the uninstall of the extension.
I know foreign keys are nice but the installer doesn't like them.
Uninstall is not in one step possible...

**Comment by m-vo** [comment]
That's currently a limitiation of the Contao Install tool. As you know foreign key constraints do not only cater for data integrity but also allow cleanup cascades - we should really use them (and some day in the core as well). :smile: 

All works fine if you use the right order<sup>*)</sup>:
- first only select the `DROP FOREIGN KEY ...` entries (or everything in the modify section)
- run the update
- select the `DROP TABLE ...` entries
- run the update again

Please open a ticket in the Contao repo as I agree this should work with less trouble ('in one step').

<sup>*)</sup> btw.: That's not the only case where the order matters. Contao for instance proposes altering columns together with the respective `CREATE TABLE` statements which fails if you deselect the latter.

**Comment by m-vo** [comment]
I'm closing this for now as there is not much that I can do on my side I guess. Do you want to open a ticket / FR in the contao/contao repository?
