### ISSUE TITLE
requestQuotaLog nullable

### ISSUE THREAD

**Issue by rabauss** [m-vo/contao-facebook-import#9]
If I create a new facebookNode in version 3.0 I get errors, that there is no default value for requestQuotaLog (depending on sqlMode). so this property should be nullable!

https://github.com/m-vo/contao-facebook-import/blob/9a56a8a83b70cbadd4071e1765fcd943585a8d5f/src/Entity/FacebookNode.php#L68

**Comment by m-vo** [comment]
fixed in v3.0.3
